FROM maven:3.9.2-eclipse-temurin-17 AS build

WORKDIR /app 

COPY . .

RUN mvn package  
 


FROM amazoncorretto:17-alpine3.20

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar" ]


